# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import depthrender_pb2 as depthrender__pb2


class DepthRenderStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetCameraParams = channel.unary_unary(
                '/depthrender.DepthRender/SetCameraParams',
                request_serializer=depthrender__pb2.SetCameraParamsRequest.SerializeToString,
                response_deserializer=depthrender__pb2.SetCameraParamsReply.FromString,
                )
        self.RenderDepthImage = channel.unary_unary(
                '/depthrender.DepthRender/RenderDepthImage',
                request_serializer=depthrender__pb2.RenderDepthImageRequest.SerializeToString,
                response_deserializer=depthrender__pb2.RenderDepthImageReply.FromString,
                )


class DepthRenderServicer(object):
    """The greeting service definition.
    """

    def SetCameraParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenderDepthImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DepthRenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetCameraParams': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCameraParams,
                    request_deserializer=depthrender__pb2.SetCameraParamsRequest.FromString,
                    response_serializer=depthrender__pb2.SetCameraParamsReply.SerializeToString,
            ),
            'RenderDepthImage': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderDepthImage,
                    request_deserializer=depthrender__pb2.RenderDepthImageRequest.FromString,
                    response_serializer=depthrender__pb2.RenderDepthImageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'depthrender.DepthRender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DepthRender(object):
    """The greeting service definition.
    """

    @staticmethod
    def SetCameraParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/depthrender.DepthRender/SetCameraParams',
            depthrender__pb2.SetCameraParamsRequest.SerializeToString,
            depthrender__pb2.SetCameraParamsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RenderDepthImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/depthrender.DepthRender/RenderDepthImage',
            depthrender__pb2.RenderDepthImageRequest.SerializeToString,
            depthrender__pb2.RenderDepthImageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
